version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Etc/UTC
    commit-message:
      prefix: build
      include: scope
    groups:
      development-dependencies:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: Etc/UTC
    commit-message:
      prefix: build
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Etc/UTC
    commit-message:
      prefix: build
      include: scope
